Repository CMU-17313Q/nodebb-f24-swifties, pull requests merged in 2024-10, with the labels that each got.

#87 User story6 frontend
  node_modules_real/post-menu-list.tpl
Labels: enhancement

#89 Uploading Automated tests - Tests.js and jest.config.js
  jest.config.js
  node_modules_real/post-menu-list.tpl
  node_modules_real/topics_list.tpl
  public/scss/chats.scss
  src/views/partials/chats/message.tpl
  test/mocks/plugin_modules/@nodebb/nodebb-additions/tests.js
Labels: enhancement

#90 Anonymous posting front end
  node_modules_real/composer-title-container.tpl
  node_modules_real/post-menu-list.tpl
  node_modules_real/post.tpl
  node_modules_real/topics_list_updated.tpl
Labels: enhancement

#91 Update topics.js
  src/routes/write/topics.js
Labels: enhancement

#98 Integrated Flow for static checking
  .babelrc
  .flowconfig
Labels: Tools Installation

#99 Integrated tool called Stryker Mutator
  .babelrc
  .gitignore
  install/package.json
  stryker.config.mjs
Labels: Tools Installation

#100 Added JSHint developer tool
  install/package.json
Labels: Tools Installation

#102 Added developer tool called Prettier
  .prettierignore
  .prettierrc
  install/package.json
  src/categories/delete.js
Labels: Tools Installation

#103 Solving the feature issue on deployment
  .gitignore
  node_modules/nodebb-theme-harmony/templates/partials/topic/post-menu-list.tpl
Labels: bug, enhancement

#104 Solving the feature issue on deployment
  .gitignore
  install/package.json
  node_modules/nodebb-theme-harmony/templates/partials/topic/ForSaving.tpl
Labels: bug, enhancement

#108 Solution6
  .gitignore
  install/package.json
  node_modules/nodebb-theme-harmony
Labels: bug, enhancement
